# ─────────────────────────────────────────
# Nginx Ingress Controller
# Routes external traffic to services
# ─────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "90"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # API → Backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          # Admin → Backend
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          # Static files → Backend
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          # Media files → Backend
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          # Everything else → Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
