apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  SECRET_KEY: "your-django-secret-key-change-this"
  DB_PASSWORD: "StrongPassword123!"
  POSTGRES_PASSWORD: "StrongPassword123!"
